spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bksrDB?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
server:
  port: 8083